#!/bin/env python

import math
from time import sleep

capacity_file = open('/sys/class/power_supply/BAT1/charge_full')
charge_file = open('/sys/class/power_supply/BAT1/charge_now')
status_file = open('/sys/class/power_supply/BAT1/status')

stdout = open("/dev/stdout", "w")

while True:
    status_file.seek(0)
    status = status_file.read(-1).strip()

    charge_file.seek(0)
    charge = int(charge_file.read(-1))

    capacity_file.seek(0)
    capacity = int(capacity_file.read(-1))

    percent_charge = math.floor(100 * charge / capacity)
    symbols = "󰂎󰁺󰁻󰁼󰁽󰁾󰁿󰂀󰂁󰂂󰁹󰂃󰂄󰂌󰂏󰂑"

    if status != "Discharging":
        symbol = '󰂄'
    else:
        symbol = symbols[math.floor(percent_charge / 10)]

    stdout.write("{")
    stdout.write(f"\"status\":\"{status}\",")
    stdout.write(f"\"percentage\":\"{percent_charge}\",")
    stdout.write(f"\"symbol\":\"{symbol}\"")
    stdout.write("}")
    stdout.write("\n")
    stdout.flush()
    sleep(1)
