set -g default-terminal "tmux-256color"
set -g base-index 1
set -s escape-time 0
set -g mouse on

set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

bind r source-file ~/.tmux.conf

bind | split-window -h
bind - split-window -v
bind _ split-window -v
unbind '"'
unbind '%'

unbind x
bind x kill-window

set -g status on
set -g status-interval 1
set -g status-justify centre # [left | centre | right]

set -g status-right "#(echo $(date '+%R'),$(acpi | cut -d ',' -f 2))" # time, battery%

# Set the status bar position
set -g status-position top # [top, bottom]

# Set status bar background and foreground color.
set -g status-style fg="#c8d0e0",bg="#353b49"
