#!/bin/env python

from requests import get
from json import loads
from sys import argv
from re import sub
from os.path import basename


def format_html(s):
    return sub('</?[^>]*>', '', s)


if len(argv) != 2:
    print(f"usage: {basename(argv[0])} [english word]")
    exit(-1)

word = argv[1]
url = f"https://en.wiktionary.org/api/rest_v1/page/definition/{word}"

response = get(url)
json_str = response._content.decode("UTF-8")
json = loads(json_str)
deftable = {}
try:
    for o in json['en']:
        deftable[o['partOfSpeech']] = [p['definition'] for p in o['definitions']]
except KeyError:
    print("No English definitions found, displaying raw response")
    print(response)


for partOfSpeech in deftable:
    print(partOfSpeech)
    i = 1
    for definition in deftable[partOfSpeech]:
        definition = format_html(definition)
        print(f"{i}. {definition}")
        i += 1
    print("")
