#!/bin/env sh

modes=$(fw-fanctrl print list | tail -n +2 | cut -c 3-)
printf "$modes" | rofi -dmenu -p 'Fan Profile' | xargs fw-fanctrl use
eww update fanprofileVar="$(fw-fanctrl print current | head -n 1 | cut -d"'" -f2)"

