#!/bin/env sh

coversdir="$HOME/media/AlbumArt/"
flag="/tmp/getart"

player="$(getplayer)"
playerctl -l | grep "^$player$" > /dev/null || echo "$coversdir/.default" exit


download() {
    coverurl=$(playerctl -p $player metadata mpris:artUrl)
    cover=${coverurl##*/}
    coverfile="$(realpath "$coversdir/$cover")"

    if [[ ! -d $coversdir ]]; then
        mkdir $coversdir
    fi
    if [[ ! -e $coverfile ]]; then
        if [[ -e $flag ]]; then
            echo "download in progress" > /dev/stderr
        else
            touch $flag
			curl "$coverurl" -o "$coverfile"
            rm $flag
        fi
    fi
    echo $coverfile
}

usage() {
    echo "USAGE"
    echo "$(basename "$0"): [-l]"
}

if [[ $# -eq 0 ]]; then
    download
elif [[ $# -eq 1 ]]; then
    if [ "$1" == "-l" ]; then
        while true; do
            download
            sleep 0.5
        done
	elif [ "$1" == "-h" ]; then
        usage
    else
        usage
		exit -1
    fi
else
    usage
	exit -1
fi
