#!/bin/env sh

pactl set-sink-mute @DEFAULT_SINK@ toggle
pactl get-sink-mute @DEFAULT_SINK@
eww update "volume_muted=$(pactl get-sink-mute @DEFAULT_SINK@ | grep 'yes' > /dev/null && echo true || echo false)"
