#!/bin/env sh

pactl set-sink-mute @DEFAULT_SINK@ toggle
mute_led="/sys/devices/platform/thinkpad_acpi/leds/platform::mute/brightness"
ledbrightness=$(pactl get-sink-mute @DEFAULT_SINK@ | grep no > /dev/null && echo 0 || echo 1)
echo $ledbrightness | sudo tee $mute_led > /dev/null

pactl get-sink-mute @DEFAULT_SINK@
