#!/bin/env sh

if [[ $(playerctl -l) == "" ]]; then
	echo "No players"
	exit
fi

playerfile="$XDG_RUNTIME_DIR/current_player"

if [[ ! -f $playerfile ]]; then
	touch $playerfile
fi

if [[ $(cat $playerfile) == "" ]]; then
	echo "playerdontexist" > $playerfile
fi

player=$(cat $playerfile)
if [[ ! $(playerctl -p $player status 2> /dev/null) ]]; then
	echo "Player \"$player\" does not exist"
	new=$(playerctl -l | head -n 1)
	player=$new
	echo $player > $playerfile
	echo "New player selected: \"$player\""
fi

status=$(playerctl -p $player status | tr -d '\n')

playerctl -p $player play-pause


icon=""
if [[ $status == "Playing" ]]; then
	status="Paused"
	icon="media-playback-pause"
elif [[ $status == "Paused"  ]]; then
	status="Playing"
	icon="media-playback-start"
fi

msg=\
"Player $player status: $status
$(playerctl -p $player metadata xesam:title) - $(playerctl -p $player metadata xesam:album)
$(playerctl -p $player metadata xesam:artist)"

if [[ -f $XDG_RUNTIME_DIR/media_notif_id ]]; then
	notify-send "$msg" --icon=$icon -r $(cat $XDG_RUNTIME_DIR/media_notif_id)
else
	touch $XDG_RUNTIME_DIR/media_notif_id
	notify-send "$msg" --icon=$icon -p | sudo tee $XDG_RUNTIME_DIR/media_notif_id
fi



