#!/bin/env sh

if [[ $(playerctl -l) == "" ]]; then
	echo "No players"
	exit
fi

playerfile="$XDG_RUNTIME_DIR/current_player"

if [[ ! -f $playerfile ]]; then
	touch $playerfile
fi

if [[ $(cat $playerfile) == "" ]]; then
	echo "playerdontexist" > $playerfile
fi

player=$(cat $playerfile)
if [[ ! $(playerctl -p $player status 2> /dev/null) ]]; then
	echo "Player \"$player\" does not exist"
	new=$(playerctl -l | head -n 1)
	player=$new
	echo $player > $playerfile
	echo "New player selected: \"$player\""
fi

player=$(cat $XDG_RUNTIME_DIR/current_player)
playerctl -p $player previous
playerctl -p $player play

