#!/bin/env sh

set -x

grim -g "$(slurp)" - > $XDG_RUNTIME_DIR/snip.png
if [[  0 -ne $? ]]; then exit; fi

name=$(rofi -dmenu -p "{}.png") \
	&& cp $XDG_RUNTIME_DIR/snip.png $HOME/$name.png \
	|| cat $XDG_RUNTIME_DIR/snip.png | wl-copy
