#!/bin/env sh

theme=$(cat /tmp/theme || echo -n default)


killall swaybg
# wall="gruv"
# swaybg --mode fill --image $WALLPAPER_DIR/$wall &
swaybg --color 1b1b1b &

killall swaync
swaync &

killall eww
eww open bar

update_colors &

tmux source ~/.config/tmux/tmux.conf &

ood=$(yes n | sudo pacman -Syu | grep "Packages ([0-9]\+)" -o | grep -o '[0-9]\+')
if [[ -z "$ood" ]]; then
	notify-send "All packages are up to date"
else
	notify-send "There are $ood out of date packages"
fi

disown
