#!/bin/env sh

theme=$(cat /tmp/theme || echo -n default)


killall swaybg
if [ $theme == "mocha" ]; then  wall="mocha"
elif [ $theme == "gruv" ]; then wall="gruv"
else                            wall="mocha"
fi

swaybg --mode fill --image $WALLPAPER_DIR/$wall &

killall swaync
swaync &

if false; then
	killall eww
	path="/home/asmi/media/AlbumArt/loop"
	if [ -f $path ]; then
		pid=$(cat $path)
		kill $pid
	fi

	eww open mainWindow &
	fish -c "while true; getart; sleep 0.8; end" > /dev/null 2> /dev/null &
	echo $! > $path
fi

update_colors &

tmux source ~/.config/tmux/tmux.conf &

disown
