#!/bin/env sh

theme=$(cat /tmp/theme || echo -n default)


killall swaybg
# wall="gruv"
# swaybg --mode fill --image $WALLPAPER_DIR/$wall &
swaybg --color 1b1b1b &

killall swaync
swaync &

killall eww
eww open bar

update_colors &

tmux source ~/.config/tmux/tmux.conf &

disown
