#!/bin/zsh

monitor=$(xrandr | grep HDMI | grep " connected" | cut -d " " -f 1)

xrandr  --output eDP-1 \
            --primary \
            --mode 1920x1080 \
            --pos 0x0 \
            --rotate normal \
        --output $monitor \
            --mode 1920x1080 \
            --pos 1920x0 \
            --rotate normal

