#!/bin/sh

gaps outer 2px
gaps inner 2px

# gaps binds
bindsym $mod+o gaps outer all plus 2
bindsym $mod+i gaps inner all plus 2
bindsym $mod+Shift+o gaps outer all minus 2
bindsym $mod+Shift+i gaps inner all minus 2
